.cargo_plain_test: &cargo_test
  stage: test
  script:
    - cargo test --verbose --jobs 1

.cargo_coverage_test: &cargo_coverage_test
  stage: test
  script:
    - cargo test --verbose --jobs 1
    - echo "kcov dir $(which kcov)"
    - for file in target/debug/pathtracer-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; kcov --exclude-pattern=/.cargo,/usr/lib "$file"; done &&
    - bash <(curl -s https://codecov.io/bash) -t 755e455c-14e8-4aeb-aded-f15272b6d352 &&
    - echo "Uploaded code coverage"

rust:stable:
  image: rustdocker/rust:stable
  <<: *cargo_coverage_test

rust:beta:
  image: rustdocker/rust:beta
  <<: *cargo_test

rust:nightly:
  image: rustdocker/rust:nightly
  <<: *cargo_test
