language: rust

# A workaround due to the Meltdown exploit
# If this can be removed in the future
# that would be amazing since this will
# increase queue times for builds
sudo: required

rust:
    - stable
    - beta
    - nightly

before_script: |
  PKGNAME="pathtracer"
  LOCAL="~/.local"
  export PATH=$LOCAL/bin:$PATH

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev

matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

cache: cargo

script:
    - cargo test --verbose --jobs 1

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build &&
  cmake -DCMAKE_INSTALL_PREFIX:PATH=$LOCAL .. && make &&
  make install && cd ../.. &&

  kcov --coveralls-id=$TRAVIS_JOB_ID \
       --exclude-pattern=/.cargo \
       target/kcov target/debug/$PKGNAME-*